# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/qtui/rpf.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 155)
        MainWindow.setMaximumSize(QtCore.QSize(410, 155))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.fileToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.fileToolButton.setObjectName("fileToolButton")
        self.gridLayout.addWidget(self.fileToolButton, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.yradioButton = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yradioButton.setFont(font)
        self.yradioButton.setObjectName("yradioButton")
        self.hasFluidGroup = QtWidgets.QButtonGroup(MainWindow)
        self.hasFluidGroup.setObjectName("hasFluidGroup")
        self.hasFluidGroup.addButton(self.yradioButton)
        self.gridLayout.addWidget(self.yradioButton, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.nradioButton = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nradioButton.setFont(font)
        self.nradioButton.setObjectName("nradioButton")
        self.hasFluidGroup.addButton(self.nradioButton)
        self.gridLayout.addWidget(self.nradioButton, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.fileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.gridLayout.addWidget(self.fileLineEdit, 0, 1, 1, 2)
        self.extractButton = QtWidgets.QPushButton(self.centralwidget)
        self.extractButton.setObjectName("extractButton")
        self.gridLayout.addWidget(self.extractButton, 3, 0, 1, 4)
        self.wellNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.wellNameInput.setObjectName("wellNameInput")
        self.gridLayout.addWidget(self.wellNameInput, 2, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 410, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "File:"))
        self.fileToolButton.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Has Fluid?"))
        self.yradioButton.setText(_translate("MainWindow", "Yes"))
        self.nradioButton.setText(_translate("MainWindow", "No"))
        self.fileLineEdit.setPlaceholderText(_translate("MainWindow", "Path of the file"))
        self.extractButton.setText(_translate("MainWindow", "Extract"))
        self.wellNameInput.setPlaceholderText(_translate("MainWindow", "Enter the well name..."))
        self.label_3.setText(_translate("MainWindow", "Well Name"))
